proyecto-compensations/force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <label>Compensation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

proyecto-compensations/force-app/main/default/objects/Compensation__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

proyecto-compensations/force-app/main/default/objects/Compensation__c/fields/Job_Category__c.field-meta.xml
<CustomField>
    <fullName>Job_Category__c</fullName>
    <inlineHelpText>Select your job category from the list or select other to enter another one</inlineHelpText>
    <label>Job Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Semi-Senior</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

proyecto-compensations/force-app/main/default/objects/Compensation__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

proyecto-compensations/force-app/main/default/objects/Compensation__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Location__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MVD WTC 2</fullName>
            </value>
            <value>
                <fullName>MVD WTC 1</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

proyecto-compensations/force-app/main/default/classes/CompensationController.cls
public with sharing class CompensationController {
    @AuraEnabled
    public static List<Compensation__c> getCompensations(){
        return [Select Id, Name, Job_Category__c, RecordType.Name, Employee__r.Name, Employee__r.Birthdate, Location__c, Amount__c, Office__c, Status__c, Submitted__c from Compensation__c];
    }
    @AuraEnabled
    public static List<Compensation__c> getByRecordType(String type){
        return [Select Id, Job_Category__c, RecordType.Name, Employee__r.Name, Employee__r.Birthdate, Location__c, Amount__c, Office__c, Status__c, Submitted__c from Compensation__c Where RecordType.Name like :type];
    }
}