proyecto-compensations/force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <label>Compensation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

proyecto-compensations/force-app/main/default/objects/Compensation__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

proyecto-compensations/force-app/main/default/objects/Compensation__c/fields/Job_Category__c.field-meta.xml
<CustomField>
    <fullName>Job_Category__c</fullName>
    <inlineHelpText>Select your job category from the list or select other to enter another one</inlineHelpText>
    <label>Job Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Semi-Senior</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

proyecto-compensations/force-app/main/default/objects/Compensation__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

proyecto-compensations/force-app/main/default/objects/Compensation__c/fields/Other_details__c.field-meta.xml
<CustomField>
    <fullName>Other_details__c</fullName>
    <label>Other details</label>
    <type>TextArea</type>
</CustomField>

proyecto-compensations/force-app/main/default/classes/TestOnSubmitted.cls
@isTest
public class TestOnSubmitted {
    @isTest static void TestSubmitCompensation() {
		saveRecords();
        Compensation__c savedComp =[select Status__c from Compensation__c where Name = 'TestCompensation'];
         System.assertEquals(savedComp.Status__c,'SUBMITTED');
    }
    
    @isTest static void TestDeleteSubmittedCompensation(){
        Compensation__c comp= saveRecords();
        Test.startTest();
        Database.DeleteResult result = Database.delete(comp, false);
        Test.stopTest();
        
         System.assert(!result.isSuccess());
        System.assert(result.getErrors().size() > 0);
        System.assertEquals('Cannot delete submitted compensation.',
                             result.getErrors()[0].getMessage());
    }
    
    static Compensation__c saveRecords(){
         Contact ct= new Contact(LastName='ExampleName');
        insert ct;
        Compensation__c comp= new Compensation__c(Name='TestCompensation', Job_Category__c='Junior', Other_details__c='', Location__c='India', Employee__c= ct.Id);
        insert comp;
        return comp;
    }
}