proyecto-compensations/force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <label>Compensation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

proyecto-compensations/force-app/main/default/objects/Compensation__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

proyecto-compensations/force-app/main/default/classes/SubmissionBatch.cls
global class SubmissionBatch implements Database.Batchable<sObject>, Schedulable {
    global Integer recordsProcessed = 0;
    public void execute(SchedulableContext context){
        Database.executeBatch(this);
    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches objects to be passed to execute
             return Database.getQueryLocator(
            'SELECT ID, Name, Location__c, CreatedDate, ' +
            'Status__c ' +
            'FROM Compensation__c ' + 
            'Where Status__c != \'Submitted\' and CreatedDate < LAST_N_DAYS:2'
        );

         }
    global void execute(Database.BatchableContext bc, List<Compensation__c> scope){
        // process each batch of records 
        List<Compensation__c> compensations = new List<Compensation__c>();
        for (Compensation__c cmp : scope) {
            cmp.Status__c= 'SUBMITTED';
            cmp.Submitted__c = true;
            recordsProcessed = recordsProcessed + 1;
        }
        update compensations;
    }    
    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
               System.debug(recordsProcessed + ' records processed!!');
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
    } 
}