proyecto-compensations/force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <label>Compensation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

proyecto-compensations/force-app/main/default/objects/Compensation__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

proyecto-compensations/force-app/main/default/objects/Compensation__c/fields/Job_Category__c.field-meta.xml
<CustomField>
    <fullName>Job_Category__c</fullName>
    <inlineHelpText>Select your job category from the list or select other to enter another one</inlineHelpText>
    <label>Job Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Semi-Senior</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

proyecto-compensations/force-app/main/default/objects/Compensation__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

proyecto-compensations/force-app/main/default/classes/TestSubmissionBatch.cls
@isTest
public class TestSubmissionBatch {
    @isTest static void test(){
         Datetime twoDaysAgo = Datetime.now().addDays(-2);
        List<Compensation__c> compensations = new List<Compensation__c>();
        Contact ct= new Contact(LastName='ExampleName');
        insert ct;
        // insert 50 compensations
        for (Integer i=0;i<50;i++) {
            Compensation__c c= new Compensation__c(name='Cmp '+i, Employee__c= ct.Id,
                Job_Category__c ='Junior', Status__c='Approved', Description__c='BatchTest', Location__c= 'India');
             compensations.add(c);

        }
        insert compensations;
        for (Compensation__c c: compensations){
            Test.setCreatedDate(c.Id, twoDaysAgo);  
        }
    
		
               
        Test.startTest();
        String CRON_EXP = '0 0 0 15 3 ? 2020';
        SubmissionBatch sb = new SubmissionBatch();
          
        Id batchId = Database.executeBatch(sb);
        Test.stopTest();
        // after the testing stops, assert records were updated properly
        System.assertEquals(50, [select count() from Compensation__c where Description__c = 'BatchTest']);
    }
}